# Generated by Django 4.2 on 2024-07-19 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_birth', models.DateField()),
                ('customer_type', models.CharField(choices=[('Company', 'Company'), ('Individual', 'Individual'), ('Proprietorship', 'Proprietorship'), ('Partnership', 'Partnership')], default=1, max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255)),
                ('customer_address', models.TextField()),
                ('sales_channel', models.CharField(choices=[('Website', 'Website'), ('Shopee', 'Shopee'), ('Lazada', 'Lazada'), ('Aliexpress', 'Aliexpress'), ('TikTok Shop', 'TikTok Shop'), ('Other', 'Other')], default=1, max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.customer')),
                ('items', models.ManyToManyField(to='products.productitem')),
            ],
        ),
    ]
